M48
; DRILL file {KiCad 6.0.4-6f826c9f35~116~ubuntu20.04.1} date N 19 mai   2022 11:10:32
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-05-19T11:10:32+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.4-6f826c9f35~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X4.4043Y-1.5275
X4.6319Y-1.5275
T0
M30
